site_name: Photo Web Documentation
site_description: Documentation for Photo Web - A web application for viewing Apple Photo Albums and documents
site_author: Photo Web Team
site_url: https://${ROOT_DOMAIN}/static/docs/
site_dir: nginx/html/static/docs

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Architecture:
    - Overview: architecture/overview.md
    - System Design: architecture/system-design.md
    - Security: architecture/security.md
  - Services:
    - Authentication: services/auth.md
    - Photos: services/photos.md
    - Files: services/files.md
  - API Reference: api-reference.md
  - Development:
    - Getting Started: development/getting-started.md
    - Guidelines: development/guidelines.md
  - Deployment:
    - Docker Setup: deployment/docker.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-repo/photo-web